import scrapy

class ProductItem(scrapy.Item):
    unique_id = scrapy.Field()
    product_name = scrapy.Field()
    brand = scrapy.Field()
    category = scrapy.Field()
    regular_price = scrapy.Field()
    selling_price = scrapy.Field()
    promotion_description = scrapy.Field()
    breadcrumb = scrapy.Field()
    pdp_url = scrapy.Field()
    product_description = scrapy.Field()
    currency = scrapy.Field()
    color = scrapy.Field()
    size = scrapy.Field()
    rating = scrapy.Field()
    review = scrapy.Field()
    material_composition = scrapy.Field()
    style = scrapy.Field()
    care_instructions = scrapy.Field()
    feature = scrapy.Field()
    images = scrapy.Field()
    composition = scrapy.Field()
