from mongoengine import DynamicDocument, StringField, BooleanField, DateTimeField
from datetime import datetime, timezone

class CategoryUrlItem(DynamicDocument):
    """Category URL collection"""
    
    url = StringField(required=True)
    name = StringField()
    parent_url = StringField()
    level = StringField()
    timestamp = DateTimeField(default=lambda: datetime.now(timezone.utc))
    
    meta = {"collection": "category_urls", "db_alias": "default"}


class ProductUrlItem(DynamicDocument):
    """Product URL collection"""
    
    url = StringField(required=True)
    category_url = StringField()
    timestamp = DateTimeField(default=lambda: datetime.now(timezone.utc))
    
    meta = {"collection": "product_urls", "db_alias": "default"}


class ProductData(DynamicDocument):

    unique_id = StringField(required=True, unique=True)
    competitor_name = StringField(default="")
    store_name = StringField(default="")
    store_addressline1 = StringField(default="")
    store_addressline2 = StringField(default="")
    store_suburb = StringField(default="")
    store_state = StringField(default="")
    store_postcode = StringField(default="")
    store_addressid = StringField(default="")
    extraction_date = DateTimeField(default=lambda: datetime.now(timezone.utc))
    
    product_name = StringField(default="")
    brand = StringField(default="")
    brand_type = StringField(default="")
    grammage_quantity = StringField(default="")
    grammage_unit = StringField(default="")
    drained_weight = StringField(default="")
    
    producthierarchy_level1 = StringField(default="")
    producthierarchy_level2 = StringField(default="")
    producthierarchy_level3 = StringField(default="")
    producthierarchy_level4 = StringField(default="")
    producthierarchy_level5 = StringField(default="")
    producthierarchy_level6 = StringField(default="")
    producthierarchy_level7 = StringField(default="")
    
    regular_price = StringField(default="")
    selling_price = StringField(default="")
    price_was = StringField(default="")
    promotion_price = StringField(default="")
    promotion_valid_from = StringField(default="")
    promotion_valid_upto = StringField(default="")
    promotion_type = StringField(default="")
    percentage_discount = StringField(default="")
    promotion_description = StringField(default="")
    package_sizeof_sellingprice = StringField(default="")
    per_unit_sizedescription = StringField(default="")
    price_valid_from = StringField(default="")
    price_per_unit = StringField(default="")
    multi_buy_item_count = StringField(default="")
    multi_buy_items_price_total = StringField(default="")
    currency = StringField(default="EUR")
    
    breadcrumb = StringField(default="")
    pdp_url = StringField(default="")
    variants = StringField(default="")
    product_description = StringField(default="")
    instructions = StringField(default="")
    storage_instructions = StringField(default="")
    preparationinstructions = StringField(default="")
    instructionforuse = StringField(default="")
    country_of_origin = StringField(default="")
    allergens = StringField(default="")
    age_of_the_product = StringField(default="")
    age_recommendations = StringField(default="")
    flavour = StringField(default="")
    nutritions = StringField(default="")
    nutritional_information = StringField(default="")
    vitamins = StringField(default="")
    labelling = StringField(default="")
    grade = StringField(default="")
    region = StringField(default="")
    packaging = StringField(default="")
    receipies = StringField(default="")
    processed_food = StringField(default="")
    barcode = StringField(default="")
    frozen = StringField(default="")
    chilled = StringField(default="")
    organictype = StringField(default="")
    cooking_part = StringField(default="")
    Handmade = StringField(default="")
    max_heating_temperature = StringField(default="")
    special_information = StringField(default="")
    label_information = StringField(default="")
    dimensions = StringField(default="")
    special_nutrition_purpose = StringField(default="")
    feeding_recommendation = StringField(default="")
    warranty = StringField(default="")
    color = StringField(default="")
    model_number = StringField(default="")
    material = StringField(default="")
    usp = StringField(default="")
    dosage_recommendation = StringField(default="")
    tasting_note = StringField(default="")
    food_preservation = StringField(default="")
    size = StringField(default="")
    rating = StringField(default="")
    review = StringField(default="")
    
    file_name_1 = StringField(default="")
    image_url_1 = StringField(default="")
    file_name_2 = StringField(default="")
    image_url_2 = StringField(default="")
    file_name_3 = StringField(default="")
    image_url_3 = StringField(default="")
    
    competitor_product_key = StringField(default="")
    fit_guide = StringField(default="")
    occasion = StringField(default="")
    material_composition = StringField(default="")
    style = StringField(default="")
    care_instructions = StringField(default="")
    heel_type = StringField(default="")
    heel_height = StringField(default="")
    upc = StringField(default="")
    features = StringField(default="")
    dietary_lifestyle = StringField(default="")
    manufacturer_address = StringField(default="")
    importer_address = StringField(default="")
    distributor_address = StringField(default="")
    vinification_details = StringField(default="")
    recycling_information = StringField(default="")
    return_address = StringField(default="")
    alchol_by_volume = StringField(default="")
    beer_deg = StringField(default="")
    netcontent = StringField(default="")
    netweight = StringField(default="")
    site_shown_uom = StringField(default="")
    ingredients = StringField(default="")
    random_weight_flag = StringField(default="")
    instock = BooleanField(default=True)
    promo_limit = StringField(default="")
    product_unique_key = StringField(default="")
    multibuy_items_pricesingle = StringField(default="")
    perfect_match = StringField(default="")
    servings_per_pack = StringField(default="")
    Warning = StringField(default="")
    suitable_for = StringField(default="")
    standard_drinks = StringField(default="")
    grape_variety = StringField(default="")
    retail_limit = StringField(default="")
    
    meta = {"collection": "product_data", "db_alias": "default"}